### ISSUE TITLE
sdl2path.patch causing CIs to fail: can I help?

### ISSUE THREAD

**Issue by a-hurst** [conda-forge/pysdl2-feedstock#22]
Hi there,

I'm the current maintainer of the PySDL2 project and just noticed that it's also got its own Conda package. I had no idea!

However, I just look a look at the automatic PRs to update to the latest PySDl2 release and noticed they're failing: apparently I changed something upstream, and now your patch to make PySDL2 use Conda's SDL2 is broken. Is there anything I can do on my end to help? Ideally I'd be able to tweak things upstream so the next release is properly Conda-compatible without any patches. All I'd need to understand is where Conda stores the SDL2 binaries, and whether there's a reliable programmatic way to get that path.

Cheers,

- Austin

**Comment by dschreij** [comment]
Hi Austin,

Thanks for your input! Nice to have the official maintainer of this package visit us here :)

Conda stores dynamic libraries in the bin directory of the virtual environment, but this differs between Windows and posix based systems. The relevant lines of the patch are here

https://github.com/conda-forge/pysdl2-feedstock/blob/master/recipe/sdl2path.patch#L12-L17

although this admittedly was a hacky way to establish the PYSDL2_DLL_PATH.

When using virtual environments, conda also sets the `CONDA_PREFIX` environment variable, which points to the environment's path. Perhaps it's better to use this instead and then look inside the `/bin` (posix) or `/Library/bin` (Windows) subfolders for sdl2?

That being said, I have very little time nowadays to maintain the conda packages on my name. If you would like me to add you as a maintainer of this feedstock so you can make the necessary changes yourself, let me know!

Cheers!

**Comment by a-hurst** [comment]
Hi Daniel, 

It looks like a simple upstream fix, so I can give it a shot! I'd be happy to accept a co-maintainership for this repo, but I don't use Anaconda myself so I'll only know if it works based off the CI. The only remaining thing I'd need to know is whether Conda-installed PySDL2 should default to the system libraries if the Conda SDL2 libraries aren't available or throw an error. There's also a pysdl2-dll package now that provides a full set of up-to-date SDL2 binaries for x86 macOS, 32-bit/64-bit Windows, and x86/ARM64 Linux, so I'm not sure whether Conda SDL2 should still take precedence if that package is installed.

Also, cool to see a fellow cognitive psych researcher out here in the wild! I used to do attention and mind-wandering work, but am now starting a PhD in a lab that researches motor learning and motor imagery. I'd imagine we use PySDL2 for very similar reasons!

Cheers,

Austin

**Comment by dschreij** [comment]
Hi Austin

I just added you to the maintainers list of this recipe. you should be able to push commits to this repo now. Please let me know if you experience any trouble.

> The only remaining thing I'd need to know is whether Conda-installed PySDL2 should default to the system libraries if the Conda SDL2 libraries aren't available or throw an error.

I think the idea was to honor the `PYSDL2_DLL_PATH` if it is set, or otherwise default to the conda installed libraries. These are linked as a package dependency of pysdl2, but of course don't need to be. There wasn't any idea to refer to the system libraries as a default. Last time I checked, was that the consensus is to stick to conda built packages as much as possible, but I don't know if this is still the case.

> There's also a pysdl2-dll package now that provides a full set of up-to-date SDL2 binaries for x86 macOS, 32-bit/64-bit Windows, and x86/ARM64 Linux,

Is this from conda or pip? I think conda rarely couples its packages this strongly, but I'm not sure. Maybe @conda-forge/core can offer some advice on the way to go?

**Comment by beckermr** [comment]
Conda libraries should always take precedence in a conda environment. We cannot promise ABI compatibility otherwise and this can lead to broken stuff super fast.

**Comment by a-hurst** [comment]
> Conda libraries should always take precedence in a conda environment. We cannot promise ABI compatibility otherwise and this can lead to broken stuff super fast.

Thanks for clarifying! PySDL2 + pysdl2-dll may be a bit of an edge case though, in that Python projects using pysdl2 can (and often do) add pysdl2-dll as an optional dependency to guarantee up-to-date and fully-featured SDL2 binaries will be available to their code. Thus, if someone tries to run a pysdl2-dll dependent project in a Conda environment and Conda defaults to using its own SDL2 binaries, that may result in unexpected behaviour (e.g. a function is unavailable because Conda's binaries are older, or support for an image or sound format was not built in the Conda binaries).

As such, my suggestion is that if a user deliberately pip-installs pysdl2-dll that should take precedence, but in all other cases the Conda SDL2 binaries should be prioritized. Does that sound reasonable?

**Comment by dopplershift** [comment]
@a-hurst But we control the build of conda-forge's SDL2 binaries, so why shouldn't everything just be going through that rather than a separate pip package?

**Comment by a-hurst** [comment]
@dopplershift Maybe I'm misunderstanding how conda works. If someone pip-installs a package that depends on PySDL2 in a Conda environment, does that install the PyPI version of PySDL2 or the Conda one? The use-case I was worried about is the latter, i.e. someone installing a package developed for non-Conda Python that expects the pysdl2-dll set of the binaries but is unable to use them because Conda's PySDL2 patches this out. If it doesn't work that way, then I think I agree the Conda-only approach to SDL2 binaries makes sense.

Actually, another question: is it standard practice for a Conda package to allow using system binaries as a fallback (e.g. `sdl2_ttf` installed with brew or apt if the Conda version isn't installed), or should that also be patched out in the interest of reproducible environments?

**Comment by dopplershift** [comment]
I don't know about patching out, but the standard practice is to specify dependencies properly so that you don't have environments where relevant compiled libraries aren't installed. So PySDL2 should unconditionally depend on conda-forge's SDL2 so that whether or not `pysdl2-dll` is installed doesn't matter; whatever else should depend on `sdl2_ttf` so that it's always installed and no other copies ever matter.

**Comment by a-hurst** [comment]
@dopplershift Okay, so if a Conda user wants to use `sdl2_ttf` with PySDL2 in their project, it's the user's responsibility to specify `sdl2_ttf` as a Conda dependency for their environment. Cool, thanks! With those guidelines in place I can get to work on an upstream patch.

**Comment by dschreij** [comment]
@a-hurst that is indeed the case. I didn't specify the sdl2 libraries as default dependencies, because users may just want to install pysdl2 from conda, and then use other sdl2 dll/dylib by setting the PYSDL2_DLL_PATH env var. As @beckermr pointed out, the important advantage of conda is that all packages are built with the same compiler and versions, so ABI compatibility is warranted. I don't expect users will experience problems if they use SDL2 libs from outside conda, but there might be edge cases in which they will.

**Comment by a-hurst** [comment]
@dschreij I think everything is fixed in #23, just waiting for your go-ahead to merge! Once this repository is updated, is there anything else needed to push the new version to conda forge?

**Comment by dschreij** [comment]
Hi @a-hurst sorry for falling of the earth for a while... Looks good, so go ahead and merge. In the future, feel free to merge if your builds pass in the CI envs. I think you and they know more than I do what is good practice here.

If your builds succeed, there is nothing you need to do to get it on conda-forge. The packages will be built automatically.
